set process field on firebase steps field
codefresh-io/task-logger pull request #110
Opened 2023-01-10 16:31 UTC by kim-codefresh

2023-01-10 17:26 UTC, daniel-codefresh commented on taskLogger/StepLogger.js
> +    setLogProcess(log) {
hmm I'm not sure i like the name logProcess
I think that just "progress" or "stepProgress" would be more appropriate

2023-01-10 17:26 UTC, daniel-codefresh commented on taskLogger/composition/StepLogger.js
> +        this.loggers.forEach((logger) => {
not sure i recall, why are there many loggers? is it multiple loggers created for the same step? or are these loggers represent multiple steps?

2023-01-10 17:26 UTC, daniel-codefresh commented on taskLogger/test/StepLogger.unit.spec.js
> +            expect(stepLogger._reportLogProcess).to.have.been.calledWith();
maybe lets also add a check on the progress field it self to verify that the state is changing

2023-01-11 10:55 UTC, daniel-codefresh requested changes

2023-01-11 10:55 UTC, daniel-codefresh commented on taskLogger/firebase/StepLogger.js
> +        this.stepRef.child('process').set(this.stepProgress);
lets also change the the name of the field in firebase

2023-01-11 10:55 UTC, daniel-codefresh commented on taskLogger/firebase/rest/StepLogger.js
> +        this.restClient.set(`${this.stepRef.ref().toString()}/process`, this.logProcess)
same thing here - lets rename the resource name in the path

2023-01-11 10:55 UTC, daniel-codefresh commented on taskLogger/firebase/rest/StepLogger.js
> +        this.restClient.set(`${this.stepRef.ref().toString()}/process`, this.logProcess)
also `this.logProcess` no longer exists - please make sure that everything still works after you finish with the renames, both in firebase and in mongo/redis(offlineLogging)

2023-01-11 10:55 UTC, daniel-codefresh commented on taskLogger/redis/StepLogger.js
> +        this.writter.child('process').set(this.stepProgress);
same thing here - lets rename the field in redis too

2023-01-11 11:00 UTC, kim-codefresh commented on taskLogger/firebase/StepLogger.js
> +        this.stepRef.child('process').set(this.stepProgress);
oh right

2023-01-12 09:02 UTC, daniel-codefresh approved these changes

2023-01-12 11:57 UTC, merged